spring:
  application:
    name: eureka-server
server:
  port: 1112
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:1111/eureka/
# 在hosts文件配置域名映射
# 127.0.0.1 eureka1
# 127.0.0.1 eureka2
